src/Web.AdminMvc/Models/ErrorViewModel.cs
using System;

namespace Web.AdminMvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Web.AdminMvc/Models/RoomViewModel.cs
using ApplicationCore.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Web.AdminMvc.Models
{
	public class RoomViewModel
	{
		 
		public int Id { get; set; }
		 
		 
		public string Name { get; set; } 

		public string RoomNo { get; set; }

		public string Note1 { get; set; }
		public string Note2 { get; set; }
		public string Note3 { get; set; }
		public string Logo { get; set; }
		public string Remarks { get; set; }
		public int GuestTimeOut { get; set; }
		public RoomState State { get; set; }
			

		public RoomViewModel()
		{

		}
		public RoomViewModel(Room room) 
		{
			Id = room.Id;
			Name = room.Name;
			RoomNo = room.RoomNo;
			this.Note1 = room.Note1;
			this.Note2 = room.Note2;
			this.Note3 = room.Note3;
			this.Logo = room.Logo;
			this.GuestTimeOut = room.GuestTimeOut;
			Remarks = room.Remarks;
			this.State = room.State;
		}
	}
}

src/Web.AdminMvc/Models/TableViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.AdminMvc.Models
{
	public class Pager {
		public int limit { get; set; }
		public int page { get; set; }
	}
	public class TableViewModel
	{
		/// <summary>
		/// 
		/// </summary>
		public int code { get; set; } = 0;
		/// <summary>
		/// 
		/// </summary>
		public string msg { get; set; } = "";
		/// <summary>
		/// 
		/// </summary>
		public int count { get; set; } = 0;
		/// <summary>
		/// 
		/// </summary>
		public object data { get; set; }
	}


	public static class TableViewModelExt {
		public static JsonResult CreateJsonResult(this TableViewModel table  ) {
			return new JsonResult(table);
		}
	}
}

src/Web.AdminMvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Web.AdminMvc.Models;

namespace Web.AdminMvc.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
		}
		public IActionResult WeCome()
		{
			return View();
		}


		public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Web.AdminMvc/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Web.AdminMvc.Models;
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using ApplicationCore.Services;
using ApplicationCore.Specifications;
using Infrastructure;

namespace Web.AdminMvc.Controllers
{
    public class RoomController : Controller
    {
		private readonly IRoomRepository _roomRepository;


		public RoomController(IRoomRepository  roomRepository) {
			_roomRepository = roomRepository;


		}

		#region 列表

		public IActionResult Index()
		{

			return View();
		}


		public JsonResult GetPageList(Pager pager)
		{

			var list = _roomRepository.ListAll().ToList().Select(s => new RoomViewModel(s)).ToList();

			return new TableViewModel
			{
				code = 0,
				count = list.Count,
				data = list.OrderBy(s => s.Id).Skip((pager.page - 1) * pager.limit).Take(pager.limit),
				msg = "",
			}.CreateJsonResult();

		}

		#endregion
		 

		#region cud
		public IActionResult Create(int id)
		{
			var model = _roomRepository.GetById(id);
			if (model == null) model = new Room();
			return View(model);
		}

		[HttpPost]
		public async Task<JsonResult> Create(Room model)
		{
			try
			{
				if (ModelState.IsValid)
				{
					if (model.Id > 0)
					{
						await	_roomRepository.AddAsync(model);
					}
					else
					{
						await _roomRepository.UpdateAsync(model);
					}
					
					return Json(AjaxExtensions.CreateSuccess());
				}
				else
				{
					return Json(AjaxExtensions.CreateFail("表单验证失败"));
				}
			}
			catch (Exception ex)
			{
				return Json(AjaxExtensions.CreateFail(ex));
			}
		}

		[HttpPost]
		public async Task<JsonResult> Del(int id) {
			var room = _roomRepository.GetById(id);

			await _roomRepository.DeleteAsync(room);

			return Json(AjaxExtensions.CreateSuccess());
		}
		#endregion

		public async Task<JsonResult> Stop(int id) {
			var room =await _roomRepository.GetByIdAsync(id);
			if(room.State==RoomState.Opened)
			room.State = RoomState.Shutdown;
			else
			{
				room.State = RoomState.Opened;

			}

			 await  _roomRepository.UpdateAsync(room);

			return Json(AjaxExtensions.CreateSuccess().SetData(room));
		}

		public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Web.AdminMvc/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "后台管理";
}

@{
	Layout = null;
}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<title>直播后台</title>
	<link href="~/ThirdParty/layui/2.2.2/css/layui.css" rel="stylesheet" />
</head>
<body class="layui-layout-body">
	<div class="layui-layout layui-layout-admin">
		<div class="layui-header">
			<div class="layui-logo">直播后台</div>
			<!-- 头部区域（可配合layui已有的水平导航） -->
			<ul class="layui-nav layui-layout-left">
				<li class="layui-nav-item"><a href="">控制台</a></li>
				<li class="layui-nav-item"><a href="">商品管理</a></li>
				<li class="layui-nav-item"><a href="">用户</a></li>
				<li class="layui-nav-item">
					<a href="javascript:;">其它系统</a>
					<dl class="layui-nav-child">
						<dd><a href="">邮件管理</a></dd>
						<dd><a href="">消息管理</a></dd>
						<dd><a href="">授权管理</a></dd>
					</dl>
				</li>
			</ul>
			<ul class="layui-nav layui-layout-right">
				<li class="layui-nav-item">
					<a href="javascript:;">
						<img src="" class="layui-nav-img">
						贤心
					</a>
					<dl class="layui-nav-child">
						<dd><a href="">基本资料</a></dd>
						<dd><a href="">安全设置</a></dd>
					</dl>
				</li>
				<li class="layui-nav-item"><a href="">退了</a></li>
			</ul>
		</div>

		<div class="layui-side layui-bg-black">
			<div class="layui-side-scroll">
				<!-- 左侧导航区域（可配合layui已有的垂直导航） -->
				<ul class="layui-nav layui-nav-tree" lay-filter="test">
					<li class="layui-nav-item layui-nav-itemed">
						<a class="" href="javascript:;">所有商品</a>
						<dl class="layui-nav-child">
							<dd><a href="javascript:;">列表一</a></dd>
							<dd><a href="javascript:;">列表二</a></dd>
							<dd><a href="javascript:;">列表三</a></dd>
							<dd><a href="">超链接</a></dd>
						</dl>
					</li>
					<li class="layui-nav-item">
						<a href="javascript:;">房间管理</a>
						<dl class="layui-nav-child">
							<dd><a href="javascript:;open('@Url.Action("Index","Room")');">房间列表</a></dd>
							<dd><a href="javascript:;open('@Url.Action("Create","Room")');">房间添加</a></dd>
						</dl>
					</li>
					<li class="layui-nav-item"><a href="">云市场</a></li>
					<li class="layui-nav-item"><a href="">发布商品</a></li>
				</ul>
			</div>
		</div>

		<div class="layui-body">
			<!-- 内容主体区域 -->
			<div style="padding: 1px;">
				<iframe id="if" frameborder="no" border="0" marginwidth="0" marginheight="0" scrolling="no" allowtransparency="yes"	src="@Url.Action("WeCome")" width="100%"></iframe>
			</div>
		</div>

		<div class="layui-footer">
			 底部固定区域 
			© layui.com - 底部固定区域
		</div>
	</div>
	<script src="~/ThirdParty/jquery/1.11.0/jquery.js"></script>
	<script src="~/ThirdParty/layui/2.2.2/layui.js"></script>
	<script>
		//JavaScript代码区域
		layui.use('element', function () {
			var element = layui.element;


			resizeLayout();
		});

		function resizeLayout() {
			var v = $(".layui-body").height();
			 
			$("#if").css("height", v);
			 
		}
		function open(url) {

			$("#if").attr('src',url);
		 }
	</script>

</body>
</html>

src/Web.AdminMvc/Views/Home/WeCome.cshtml
@{
	ViewData["Title"] = "后台管理";
}

@{
	Layout = null;
}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<title>欢迎你</title>
	<link href="~/ThirdParty/layui/2.2.2/css/layui.css" rel="stylesheet" />
</head>
<body class="layui-layout-body">
	欢迎你!
	 
	<script src="~/ThirdParty/jquery/1.11.0/jquery.js"></script>
	<script src="~/ThirdParty/layui/2.2.2/layui.js"></script>
	<script>
		//JavaScript代码区域
		layui.use('element', function () {
			var element = layui.element;


		 
		});

		 
	</script>
</body>
</html>

src/Web.AdminMvc/Views/Room/Create.cshtml
@model ApplicationCore.Entities.Room
@{
	ViewData["Title"] = "添加房间";
	Layout = "~/Views/Shared/_Layout_Create.cshtml";
}
<form class="layui-form">
	<div class="layui-tab">
		<ul class="layui-tab-title">
			<li class="layui-this">基本信息</li>
			<li>控制</li>
			<li>直播配置</li>
			<li>公告相关</li>
			<li>其他</li>

		</ul>
		<div class="layui-tab-content">
			<div class="layui-tab-item layui-show">

				<div class="layui-form-item">
					<label class="layui-form-label">房间号</label>
					<div class="layui-input-block">
						<input type="text" id="RoomNo" name="RoomNo" value="@Model.RoomNo" lay-verify="required"  autocomplete="off" placeholder="" class="layui-input">
					</div>
				</div>
				<div class="layui-form-item">
					<label class="layui-form-label">房间</label>
					<div class="layui-input-block">@*lay-verify="required|phone|number"*@
						<input type="text" id="Name" name="Name" value="@Model.Name" lay-verify="required" autocomplete="off" placeholder="" class="layui-input">
					</div>
				</div>
				<div class="layui-form-item">
					<label class="layui-form-label">密码</label>
					<div class="layui-input-block">
						<input type="text" id="PassWord" name="PassWord" value="@Model.PassWord" autocomplete="off" placeholder="" class="layui-input">
					</div>
				</div>
				<div class="layui-form-item">
					<label class="layui-form-label">备注</label>
					<div class="layui-input-block">
						<input type="text" id="Remarks" name="Remarks" value="@Model.Remarks" autocomplete="off" placeholder="" class="layui-input">
					</div>
				</div>
				<div class="layui-form-item">
					<label class="layui-form-label">客服qq</label>
					<div class="layui-input-block">
						<input type="text" id="ServiceQQ" name="ServiceQQ" value="@Model.ServiceQQ" autocomplete="off" placeholder="" class="layui-input">
					</div>
				</div>
			</div>
			<div class="layui-tab-item">
				<div class="layui-form-item">
					<label class="layui-form-label">消息自动审核</label>
					<div class="layui-input-block">
						@Html.DropDownListFor(s => s.AMA, new SelectList(Enum.GetNames(typeof(ApplicationCore.Entities.AutomaticMessageAudit)), "请选择"))


					</div>
				</div>
				<div class="layui-form-item">
					<label class="layui-form-label">游客时间</label>
					<div class="layui-input-block">
						<input type="text" id="GuestTimeOut" name="GuestTimeOut" value="@Model.GuestTimeOut" autocomplete="off" placeholder="" class="layui-input">
					</div>
				</div>
				<div class="layui-form-item">
					<label class="layui-form-label">发言频率</label>
					<div class="layui-input-block">
						<input type="text" id="SpeakInterval" name="SpeakInterval" value="@Model.SpeakInterval" autocomplete="off" placeholder="" class="layui-input">
					</div>
				</div>
				<div class="layui-form-item">
					<label class="layui-form-label">状态</label>
					<div class="layui-input-block">

						@Html.DropDownListFor(s => s.State, new SelectList(Enum.GetNames(typeof(ApplicationCore.Entities.RoomState)), "请选择"))
						@*<input type="text" id="State" name="State" value="@Model.State" autocomplete="off" placeholder="" class="layui-input">*@
					</div>
				</div>
				<div class="layui-form-item">
					<label class="layui-form-label">域名</label>
					<div class="layui-input-block">
						<input type="text" id="Doman" name="Doman" value="@Model.Doman" autocomplete="off" placeholder="" class="layui-input">
					</div>
				</div>
				<div class="layui-form-item">
					<label class="layui-form-label">开始时间</label>
					<div class="layui-input-block">
						<input type="text" name="DateTimeStart" id="DateTimeStart" value="@Model.DateTimeStart.Value.ToString("yyyy-MM-dd")" lay-verify="date" placeholder="yyyy-MM-dd" autocomplete="off" class="layui-input">
					</div>
				</div>
				<div class="layui-form-item">
					<label class="layui-form-label">结束时间</label>
					<div class="layui-input-block">
						<input type="text" name="DateTimeEnd" id="DateTimeEnd" value="@Model.DateTimeEnd.Value.ToString("yyyy-MM-dd")" lay-verify="date" placeholder="yyyy-MM-dd" autocomplete="off" class="layui-input">

					</div>
				</div>

			</div>
			<div class="layui-tab-item">
				<div class="layui-form-item">
					<label class="layui-form-label">yyID号</label>
					<div class="layui-input-block">
						<input type="text" id="YYLiveId" name="YYLiveId" value="@Model.YYLiveId" autocomplete="off" placeholder="" class="layui-input">
					</div>
				</div>
				<div class="layui-form-item">
					<label class="layui-form-label">斗鱼ID号</label>
					<div class="layui-input-block">
						<input type="text" id="DYLiveId" name="DYLiveId" value="@Model.DYLiveId" autocomplete="off" placeholder="" class="layui-input">
					</div>
				</div>
				<div class="layui-form-item">
					<label class="layui-form-label">直播地址</label>
					<div class="layui-input-block">
						<input type="text" id="LiveUrl" name="LiveUrl" value="@Model.LiveUrl" autocomplete="off" placeholder="" class="layui-input">
					</div>
				</div>
			</div>
			<div class="layui-tab-item">


				<div class="layui-form-item">
					<label class="layui-form-label">滚动公告</label>
					<div class="layui-input-block">
						<input type="text" id="Scroll2Notice" name="Scroll2Notice" value="@Model.Scroll2Notice" autocomplete="off" placeholder="" class="layui-input">
					</div>
				</div>

				<div class="layui-form-item">
					<label class="layui-form-label">公告</label>
					<div class="layui-input-block">
						<input type="text" id="Note1" name="Note1" value="@Model.Note1" autocomplete="off" placeholder="" class="layui-input">
					</div>
				</div>
				<div class="layui-form-item">
					<label class="layui-form-label">版权说明</label>
					<div class="layui-input-block">
						<input type="text" id="Note2" name="Note2" value="@Model.Note2" autocomplete="off" placeholder="" class="layui-input">
					</div>
				</div>
				<div class="layui-form-item">
					<label class="layui-form-label">权限说明</label>
					<div class="layui-input-block">
						<input type="text" id="Note3" name="Note3" value="@Model.Note3" autocomplete="off" placeholder="" class="layui-input">
					</div>
				</div>
			</div>
			<div class="layui-tab-item">
				<div class="layui-form-item">
					<label class="layui-form-label">房间logo</label>
					<div class="layui-input-block">
						<input type="text" id="Logo" name="Logo" value="@Model.Logo" autocomplete="off" placeholder="" class="layui-input">
					</div>
				</div>
				<div class="layui-form-item">
					<label class="layui-form-label">在线人数</label>
					<div class="layui-input-block">
						<input type="text" id="OnlineUsers" name="OnlineUsers" value="@Model.OnlineUsers" autocomplete="off" placeholder="" class="layui-input">
					</div>
				</div>
			</div>

		</div>
	</div>


	<input type="hidden" id="Id" name="Id" autocomplete="off" value="@Model.Id" placeholder="" class="layui-input">


	<div class="layui-form-item">
		<div class="layui-input-block">
			<button class="layui-btn" lay-submit="" lay-filter="demo1">立即提交</button>
			<button type="reset" class="layui-btn layui-btn-primary">重置</button>
		</div>
	</div>
</form> 

<script>
	layui.config({
		base: '/layui/room/' //你存放新模块的目录，注意，不是layui的模块目录
	}).use('create'); //加载入口
</script> 

src/Web.AdminMvc/Views/Room/Index.cshtml
@model RoomViewModel
@using ApplicationCore.Entities;
@{
	ViewData["Title"] = "房间列表";
}

@{
	Layout = "~/Views/Shared/_Layout_Index.cshtml";
}
 
<div class="demoTable">
	搜索：
	<div class="layui-inline">
		<input class="layui-input" name="id" id="demoReload" autocomplete="off">
	</div>
	<button class="layui-btn" data-type="reload">搜索</button>
	<button class="layui-btn" data-type="add">添加</button>
</div>
<table class="layui-hide" id="list" lay-filter="demo"></table>
<script type="text/html" id="barDemo">
	<a class="layui-btn layui-btn-primary layui-btn-xs" lay-event="stop">开/关</a>
	<a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
	<a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
</script>
 <script>
	 layui.config({
		 base: '/layui/room/' //你存放新模块的目录，注意，不是layui的模块目录
	 }).use('index'); //加载入口
</script> 

src/Web.AdminMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web.AdminMvc</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Web.AdminMvc</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Web.AdminMvc</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

src/Web.AdminMvc/Views/Shared/_Layout_Create.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Web.AdminMvc</title>
	 
	<script src="~/lib/jquery/dist/jquery.js"></script> 
	<link href="~/ThirdParty/layui/2.2.2/css/layui.css" rel="stylesheet" />

	<script src="~/ThirdParty/layui/2.2.2/layui.js"></script>
</head>
<body>
	<!-- 内容主体区域 -->
	 @*@ViewData["Title"]
	<hr class="layui-bg-orange">*@
	@RenderBody()
	 

	@RenderSection("Scripts", required: false)
</body>
</html>

src/Web.AdminMvc/Views/Shared/_Layout_Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
	<title>@ViewData["Title"] - Web.AdminMvc</title>
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"> 
  

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

	<script src="~/lib/jquery/dist/jquery.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<link href="~/ThirdParty/layui/2.2.2/css/layui.css" rel="stylesheet" />

	<script src="~/ThirdParty/layui/2.2.2/layui.js"></script>
</head>
<body>
	<!-- 内容主体区域 -->
	<div style="padding: 15px;">
		
		@ViewData["Title"]
		<hr class="layui-bg-orange">
		@RenderBody()
	</div>





	@RenderSection("Scripts", required: false)
</body>
</html>